version: '2'
services:
  db:
    image: mysql:5.6
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=PEHB
    ports:
     - "3307:3306"
  web:
    image: eboraas/laravel
    volumes:
      - .:/var/www/laravel
    links:
      - db
    ports:
     - "1111:80"